replicaCount: 1
autoscaling:
  enabled: false

ingress:
  enabled: true
  className: nginx
  host: "kubernetes-course.devopsdirective.com"
  path: "/api/golang"
  tlsSecretName: ""

secrets:
  enabled: true
  vaultPath: "secret/data/dev/demo-golang-api"
