apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.name" . }}-init-sql
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  001_create_request_table.sql: |
    CREATE TABLE IF NOT EXISTS public.request (
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        api_name VARCHAR(10) NOT NULL CHECK (api_name IN ('node', 'go'))
    );
