apiVersion: v2
name: demo-node-api
description: Demo Node.js API (DevOps Directive Kubernetes course) - queries Postgres for current time + request count
type: application
version: 0.1.0
appVersion: "1.0.0"
